### ISSUE TITLE
Leader board empty

### ISSUE THREAD

**Issue by shaedrich** [foundeo/cfdocs#1028]
There seems to be something wrong with the leader board:

> 0 AWESOME CONTRIBUTORS

**Comment by pfreitag** [comment]
Hmm, can you reload and see if it is still like that, it must just be in your edge location because it is working fine for me. I think when there is an error loading leaderboard it will set the cache TTL very low, so it should fix itself soon (I think).

**Comment by shaedrich** [comment]
It works again! Thanks.
