### ISSUE TITLE
cfpdf

### ISSUE THREAD

**Issue by mtotowamkwe** [foundeo/cfdocs#1040]
I get a not supported yet error when I try to use the action="extracttext" of the cfdpf tag. Has this issue been fixed?
My Lucee version is 5.1.2.24
My ColdFusion version is 2016,0,03,300357

`

Lucee 5.1.2.24 Error (application)
--
Message | not supported yet, see https://issues.jboss.org/browse/LUCEE-1559

`

**Comment by pfreitag** [comment]
Here is the correct ticket link for lucee: https://luceeserver.atlassian.net/browse/LDEV-1941 maybe we should add a link to this ticket on the cfpdf doc page.

**Comment by pfreitag** [comment]
looks like it has been fixed in recent versions
