### ISSUE TITLE
Replace CDN RawGit

### ISSUE THREAD

**Issue by shawnoden** [foundeo/cfdocs#1043]
Looking through the source, RawGit is being used as a CDN. The home page for RawGit (https://rawgit.com/) indicates that it is EOL and will cease to function in October 2019. Links using this service will need to be changed.

**Comment by shaedrich** [comment]
Can't we just shorten [https://cdn.rawgit.com/foundeo/cfdocs/3da43f03663c57f499cf2de82ef82d4f74fe04cd/assets/vendor/google/code-prettify/theme-monokai.css](https://cdn.rawgit.com/foundeo/cfdocs/…/assets/vendor/google/code-prettify/theme-monokai.css) to [`#request.assetBaseURL#`/vendor/google/code-prettify/theme-monokai.css](https://cfdocs.org/assets/v-21c02397f48b98a9ddd999e58f9c7c92/style.css)

**Comment by shawnoden** [comment]
The file is there, but then Foundeo would be hosting it and would have to deal with that bandwidth. Plus, we'd probably want to minify it, too. Also looks like the Fork Me On Github png is hosted through Rawgit.

**Comment by shaedrich** [comment]
I already changed the image to a css styled text ribbon. theme-monokai.css is a theme for the code examples in the docs.

**Comment by pfreitag** [comment]
Ok thanks @shaedrich - I bet we can use another JS cdn for code-prettify: prettify.js it is probably on npm

**Comment by shaedrich** [comment]
So, should we use this one?
https://cdn.jsdelivr.net/gh/foundeo/cfdocs@3da43f03663c57f499cf2de82ef82d4f74fe04cd/assets/vendor/google/code-prettify/theme-monokai.css

**Comment by pfreitag** [comment]
@shaedrich yup that should work

**Comment by shaedrich** [comment]
Why doesn't [`#request.assetBaseURL#`/vendor/google/code-prettify/theme-monokai.css](https://cfdocs.org/assets/v-21c02397f48b98a9ddd999e58f9c7c92/style.css) work?

**Comment by pfreitag** [comment]
Yeah that works too, was just using rawgit to offload the bandwidth, since that file is really third party I don't expect it to change. 

Also this was before http/2 - it might be faster now with http/2 to have all assets loaded from the same origin.

**Comment by shaedrich** [comment]
Hmmm… So we should use jsdelivr instead of our file and completely remove it from the repo?

**Comment by pfreitag** [comment]
If you are using the above link then you should not delete the file from this repo because it is pulling from this repo.

Let's try switching the theme up a bit: https://cdn.jsdelivr.net/npm/color-themes-for-google-code-prettify@2.0.4/dist/themes/tomorrow-night-bright.min.css

Here is more info about the theme: https://jmblog.github.io/color-themes-for-google-code-prettify/ it looks like it is maintained.

Also prettify itself could be loaded via this: https://cdn.jsdelivr.net/npm/code-prettify@0.1.0/loader/prettify.js

**Comment by shaedrich** [comment]
You you want to switch from "monokai" to "tomorrow night bright"?
