### ISSUE TITLE
CF Function: EncodeFor()

### ISSUE THREAD

**Issue by shawnoden** [foundeo/cfdocs#1072]
`EncodeFor` was previously added as an attribute to a couple of tags, like `cfoutput`, but Adobe ColdFusion 2016 and 2018 also have an `EncodeFor(type,value)` function. Essentially the same as specific `encodeForHTML`/`encodeForJavascript`/etc.

```
<cfscript>
    str = "<br>" ;
    es = encodeFor("HTML",str) ; // Works in CF2016 & 2018
    
    writeDump(es) ;
    writeDump( encodeFor(type="HTML",value=str) ) ; // Works in CF2018
</cfscript>
```
It can be called with unnamed attributes in both CF2016 and CF2018, and CF2018 will also work with named attributes. It doesn't work if used as a member function. And it doesn't seem to allow the `canonicalize` attribute in the other `EncodeFor*()` functions.  It doesn't work in Lucee. 

This function isn't documented in the ACF docs, but it is included on the NamedParametersColdFusion2018.pdf document. Other than that reference, I can't find anything else about that actual function. It also doesn't seem to be coming from Java, so I'm not sure how it's reaching into the language.

My gut feeling is that it should stay undocumented in CFDocs, since the others are there and should be used instead. Does anyone else think it should be added to CFDocs? Or should it continue to be an undocumented function?

**Comment by KamasamaK** [comment]
It's included in the `getFunctionList()` for CF2016+ also, so I think it should be documented.

**Comment by pfreitag** [comment]
Yes Just tested it and it works on CF2016 and CF2018 - lets add it.

**Comment by pfreitag** [comment]
Link to NamedParametersColdFusion2018.pdf for reference: http://cfdownload.adobe.com/pub/adobe/coldfusion/2018/publicBeta/NamedParametersColdFusion2018.pdf

**Comment by shawnoden** [comment]
To add it, do I just create a new JSON doc for it? Does anyone know anywhere that there's documentation for it? If not, I'll just leave the "engines:{docs}" field blank.

**Comment by pfreitag** [comment]
@shawnoden yeah just create a new json file for it... you should still put in the engines key for `coldfusion`, I would just link the doc to the NamedParametersColdFusion2018.pdf for now... once Adobe adds a doc page we will update it.

**Comment by shawnoden** [comment]
Completed in PR #1073. I'll also make the changes KamasamaK suggested.
