### ISSUE TITLE
queryEach

### ISSUE THREAD

**Issue by jwkoehler** [foundeo/cfdocs#1117]
Example code does not work. Missing semi colon after row.id line. Also, QueryEach does not return anything so it can not be output. Should be moved into the cfscript block and have WriteOutput("<table>") and WriteOutput("</table>") surrounding it. Then the code will work. What does the outputting is the newsRow function, not the QueryEach function. The whole cfoutput block at the end of the sample code isn't needed and doesn't work.

**Comment by pfreitag** [comment]
Fixed in #1156
