### ISSUE TITLE
"This tag/function requires" - engine not supported

### ISSUE THREAD

**Issue by shaedrich** [foundeo/cfdocs#1146]
# Current situation
When we display the message mentioned in the title but the engine is not supported, the sentence ends after "requires" without mentioning the required engine.

It seems like we deprecated the other engines so that the ifs only result in supported engines, but we weren't consistent enough to remove the message itself.

https://github.com/foundeo/cfdocs/blob/eb4b57a1b1980f14cdaa35d1c5765959fad23d46/views/doc.cfm#L70-L80

# Examples
- [structListNew](https://cfdocs.org/structlistnew)
- [structValueArray](https://cfdocs.org/structvaluearray)

# Which solution do we choose?
- Removing the message for other engines
- Extend the ifs to cover the other engines as well

Solution 1 seems odd because the link to the docs appears anyway.

# Additional questions
- Why are even ACF and Lucee inconsistent?
    - While ACF lists the exact version number whereas Lucee does not
    - While ACF says "Not supported on Lucee, OpenBD, etc.", Lucee only says "Not supported on Adobe ColdFusion." and that's it

**Comment by pfreitag** [comment]
I'd say extend the IF's to cover other engines. Not sure why version number is left off of Lucee, that could be added in. 

For _ Not supported on Adobe ColdFusion_ I suppose we could also add or OpenBD, but I think the usage of OpenBD is so small, I'm ok leaving that as is. I don't want OpenBD look as if it is more prevalent that it actually is (last stable release appears to have been in 2014).

**Comment by shaedrich** [comment]
Okay, let's take OpenBD out of the message for ACF as well to have it consistent.

**Comment by shaedrich** [comment]
Okay, the pr is ready for review :wink:
