### ISSUE TITLE
fixing order of "guides" drop-down display

### ISSUE THREAD

**Issue by carehart** [foundeo/cfdocs#1170]
As some may have noticed, the "Guides" drop-down is in not in alpha order. I looked into changing it, seeing it is controlled by an array in data/en/guides.json. The issue is that while the values listed there ARE in sorted order, that's the file NAMES holding each guide. The guide TITLES are not reflected in that filename alpha ordering:

`related":["application","cfsqltype-cheatsheet","cgi-scope","closures","coldfusion-versions","datetime","elvis","error-handling","first_class","for","java","member","new","operators","ormsettings","scopes","script","security","security-authentication","security-encryption","security-obfuscation","security-session-management","system-properties","testbox","variables-scope"]`

And of course, one could try to manually figure out what the sort order would be, by the TITLEs, and change that list of array values. 

But I'm wondering if there may be some automated process which **might end up reversing things back to the file-name order**, if/when someone added a new guide to the site.

If that's the case, I just wanted to bring up this issue in the hopes that some consideration might be given to what may be the best way to handle this issue. 

Could this be the solution: **could such an automated indexing operation instead simply sort the values in that JSON "related" array by the TITLE in the files (the first # line in the md file)?** (I tried to find such indexing code but missed it, if it exists.)

**Comment by shaedrich** [comment]
I don't think, it makes much sense to order this array when it is created by something technically unrelated at this moment. In my opinion it would make more sense to order it when outputting the drop-down based on the titles.

Let's see, what @pfreitag thinks about that.

**Comment by carehart** [comment]
Sebastian, can you clarify what you mean by "something technically unrelated "?

As for your agreement with ordering it by title, the challenge again is that the drop-down is formed by that json array I pointed to, which only has the filenames and is ordered by them. So the whole point of my issue is to ask how we can get it to instead be ordered by title. (Maybe you are suggesting that the title be added to the json? That's an option, though with some complication.)

But yep, looking forward to hearing from Pete or anyone involved in the background processing/building of the site files.

**Comment by shaedrich** [comment]
Well, we've three possible scenarios then:

1. **Sorting the JSON during adding/removing guides**:
Possible, but it might not clear to everyone who reads the code, why it is sorted by the title, because it has no relation to that part of the code
2. **Providing additional infos such as title in the JSON**:
If not absolutely necessary, we shouldn't change the existing data structure. That would create an array of structures instead of an array of strings.
3. **Sorting the JSON during outputting the menu**:
Because we display the title at this point anyway, we already have it extracted and can also use it to sort the JSON with nearly no extra code.

**Comment by pfreitag** [comment]
Hi @carehart - there is an indexer which does create some json files dynamically, it is located here:

https://github.com/foundeo/cfdocs/blob/master/utilities/indexer.cfm

The guides are indexed at runtime and stored in an application.guides variable, defined here:

https://github.com/foundeo/cfdocs/blob/master/Application.cfc#L23-L34

The `application.guides` variable is currently sorted again in the layout view on line 23:

https://github.com/foundeo/cfdocs/blob/master/views/layout.cfm#L23

It would probably make the most sense to sort it once when `application.guides` is defined and then not sort it again in the view.

**Comment by carehart** [comment]
Thanks, Pete. Is that something you would take on? Or are you leaving it for others to look into? I just can't tell from your reply, and I want to help avoid duplication of effort if someone else is motivated/has time (I'm about to go on some travel so can't commit to it in coming days).

**Comment by pfreitag** [comment]
@carehart - this is not something I would be able to get into in the immediate future either, so if someone wants to take it on, feel free.

@shaedrich - I think option 3 sounds like the way to go for now, I don't want to mess with the json structures unless needed as well.

**Comment by shaedrich** [comment]
So if you @carehart don't want to implement this, I volunteer for it.

**Comment by carehart** [comment]
Oh, sure. Please do, thanks. Sorry, I lost track of it. (Lots going on in the run up to CF Summit and then CF Camp.)



/charlie

**Comment by shaedrich** [comment]
No problem, me too :D

**Comment by carehart** [comment]
Guys, I happened upon this issue again. Is it that the fix offered last year didn't work or just hasn't been put I to place on the site?
