### ISSUE TITLE
cfschedule - Clarify supported attributes standard vs enterprise

### ISSUE THREAD

**Issue by bshea5** [foundeo/cfdocs#1173]
I'd like to propose an addition in the documentation that refers to what attributes of this tag are supported in Adobe standard edition, vs enterprise edition. An example, the onMisfire attribute is only supported in the enterprise edition.

https://www.adobe.com/uk/products/coldfusion-family/buying-guide.html

Thank you,

Brandon Shea

**Comment by shaedrich** [comment]
Maybe the version label needs an additional (optional) indicator …

**Comment by andrew-dixon** [comment]
So the items the buyer guides lists as not supported by standard relating to scheduled tasks are:

- Misfire and exception handling of scheduled tasks
- Listeners for scheduled tasks
- Cluster support for scheduled tasks
- Chaining of scheduled tasks
- Application-specific scheduled tasks

Looking at the tag, I think it would be these:

`onComplete`
`onException`
`onMisfire`
`eventHandler`
`cluster`
`mode` (maybe only if you try and set it to `application`, not sure)

**Comment by pfreitag** [comment]
Thanks @andrew-dixon yes I agree let's just add a text note to the attributes/features that are only supported on enterprise.

**Comment by brianconner** [comment]
opened PR 1360

**Comment by shawnoden** [comment]
This appears to have been completed and can be closed.

**Comment by pfreitag** [comment]
thx @shawnoden
