### ISSUE TITLE
generatePBKDFKey

### ISSUE THREAD

**Issue by GeoffCapper** [foundeo/cfdocs#1293]
According to official CF docs (and use seems to confirm) keySize should be in bits. Cfdocs has "The length in bytes of the key to generate", which should be "The length in bits of the key to generate". It also includes a values section with boolean values underneath.

**Comment by shaedrich** [comment]
Can you post the link where you read this to reduce additional research for the one, who might want to open a pr?

**Comment by pfreitag** [comment]
I concur - it should say bits, not bytes thanks @GeoffCapper

**Comment by GeoffCapper** [comment]
I've put through a PR to fix this. Direct link to page is https://cfdocs.org/generatepbkdfkey
