### ISSUE TITLE
FileUpload example code error

### ISSUE THREAD

**Issue by cfcoder** [foundeo/cfdocs#1315]
Just wanted to point out that the snippet of example code for FileUpload function has a small error.
https://cfdocs.org/fileupload

It refers to cffile.serverFileExt but it should actually be uploadedFile.serverFileExt since that is the variable name where the results of the fileUpload went.

**Comment by Dharcf** [comment]
Hi @cfcoder & Foundeo
I've changed the variable name & tested in my local test page. It's working fine. Please check it and confirm. Thanks.

**Comment by pfreitag** [comment]
Fixed, thanks @Dharcf

**Comment by teaman** [comment]
@Dharcf Thank you
