### ISSUE TITLE
Incorrect options for GETASBINARY attribute (ACF)

### ISSUE THREAD

**Issue by bshea5** [foundeo/cfdocs#1365]
Get the following when trying to use 'true' as either a string or a primitive. CFDocs describes both true and false as valid inputs, but ACF does not accept them.

Description: Attribute validation error for CFHTTP.The value of the GETASBINARY attribute is invalid. The value must be one of YES, NO, NEVER, or AUTO.

**Comment by pfreitag** [comment]
Thanks - I filed a bug with adobe, works on lucee: https://tracker.adobe.com/#/view/CF-4212084
