### ISSUE TITLE
createObject

### ISSUE THREAD

**Issue by cfcoder** [foundeo/cfdocs#1369]
It shows all parameters as "Required". I think only the first two are required, at least for type "component".

**Comment by KamasamaK** [comment]
It's not all parameters that are marked as required. The problem is that each of those required parameters that aren't `type` are the different names of the second parameter that depend on `type`. The root issue is actually lack of support for multiple signatures (See #529).

**Comment by cfcoder** [comment]
Perhaps a different method of display where parameters that are required are marked as conditionally required depenedent on the type?

**Comment by KamasamaK** [comment]
@cfcoder I think that would still generally fall under #529. Any other solution would be too specific/narrow.

**Comment by teaman** [comment]
I agree with you. You can close this one

**Comment by cfcoder** [comment]
@KamasamaK I somehow missed your reference to 529. I agree that One covers this issue.
