### ISSUE TITLE
cfpdf 404ing?

### ISSUE THREAD

**Issue by neokoenig** [foundeo/cfdocs#1370]
https://cfdocs.org/cfpdf appears to be 404ing even though https://github.com/foundeo/cfdocs/blob/master/data/en/cfpdf.json exists?

**Comment by KamasamaK** [comment]
Works for me

**Comment by neokoenig** [comment]
Curious... not for me!

![image](https://user-images.githubusercontent.com/381268/104125394-572c2f00-534e-11eb-90e5-add3387d6389.png)

**Comment by pfreitag** [comment]
Thanks for letting me know @neokoenig! This should be fixed now.
