### ISSUE TITLE
/cfapplication links to wrong page

### ISSUE THREAD

**Issue by XylianZeref** [foundeo/cfdocs#1373]
In https://cfdocs.org/cfapplication we have a red box where Application.cfc links to the non existing page https://cfdocs.org/application%2Dcfc
We should link to the existing page https://cfdocs.org/application instead.

**Comment by pfreitag** [comment]
Actually https://cfdocs.org/application-cfc is the correct page but it wasn't loading properly on the server, that is fixed now.

**Comment by pfreitag** [comment]
Thanks for reporting the issue @XylianZeref !!
