### ISSUE TITLE
getCanonicalPath trailing slash not guaranteed?

### ISSUE THREAD

**Issue by softwareCobbler** [foundeo/cfdocs#1377]
i don't see "if a directory a trailing slash is always used" on Adobe's official docs, and running the following on [trycf.com/?engine=acf2018](https://www.trycf.com/?engine=acf2018):

`writeDump(getCanonicalPath(getDirectoryFromPath(getCurrentTemplatePath())))`

returns `/tmp`

So I don't believe a trailing slash is always (ever?) appended to a directory name.

**Comment by pfreitag** [comment]
Thanks @softwareCobbler the docs have been updated to reflect this. Unfortunately ACF and Lucee behave differently here.
