### ISSUE TITLE
Lucee 5 ExtensionExists() method #hacktoberfest

### ISSUE THREAD

**Issue by michaelborn** [foundeo/cfdocs#1401]
Lucee 5 offers this handy-dandy quick method to see if a particular extension is installed. You can even pass a version string to check if a specific version is installed.

## Syntax

* `extensionExists( "FAD1E8CB-4F45-4184-86359145767C29DE" );`
* `extensionExists( "FAD1E8CB-4F45-4184-86359145767C29DE", "3.5.5.77" );`

## Example

```js
var hibernateExtensionID = "FAD1E8CB-4F45-4184-86359145767C29DE";
if ( !extensionExists( hibernateExtensionID ) ){
  throw( "Please install the Hibernate extension now.");
} else if ( !extensionExists( hibernateExtensionID, "3.5.5.77" ) ){
  throw( "Your Hibernate extension is outdated; please upgrade now." );
}
```

https://github.com/lucee/Lucee/blob/5.3.8/core/src/main/java/lucee/runtime/functions/system/ExtensionExists.java#L23

**Comment by pfreitag** [comment]
Nice! thanks for posting details @michaelborn 

For anyone looking to add this, you'll need to add a new json file to the `data/en` directory to document the function.

**Comment by michaelborn** [comment]
Time to close this issue, as #1432 is merged?

**Comment by pfreitag** [comment]
yes, thanks for the nudge @michaelborn

**Comment by KamasamaK** [comment]
@shawnoden For future reference, if your pull request will resolve an issue then you should put the word "[Fixes/Resolves/Closes](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests)" before the issue number in the PR so it will automatically close the issue when merged.

**Comment by shawnoden** [comment]
@KamasamaK Will do. Thanks for letting me know that. I knew there was some way to auto-close issues, but didn't know what it was. 

This might be a handy tip to add to the Contributing docs.  I'll try to add an issue for that (or  do a PR myself) for that later.
