### ISSUE TITLE
DateFormat updates for CF2021

### ISSUE THREAD

**Issue by tylergleave** [foundeo/cfdocs#1448]
ColdFusion 2021 added support for the "D" and "M" masks in the DateFormat function.

D returns the day of the year.
M returns the month in the year.

https://tracker.adobe.com/#/view/CF-4210921
https://helpx.adobe.com/coldfusion/cfml-reference/coldfusion-functions/functions-c-d/DateFormat.html

**Comment by pfreitag** [comment]
The `M` is done, still need to add `D` I think

**Comment by KamasamaK** [comment]
I think this is done. I'm not sure where else this should be documented.

**Comment by pfreitag** [comment]
thanks!
