### ISSUE TITLE
cfqueryparam

### ISSUE THREAD

**Issue by YPDS** [foundeo/cfdocs#1454]
To aid in understanding cfqueryparam for a newcomer, it may be useful to reiterate this example from your queryExecute document.

`qryResult = queryExecute("SELECT * FROM Employees WHERE empid = :empid AND country = :country", {country={value="USA", cfsqltype="cf_sql_varchar"}, empid={value=1, cfsqltype="cf_sql_integer"}});`

This one explains how a **defined** cfqueryparam, not an array, would be written. Moreover, it displays how multiple cfqueryparam values can be defined in cfscript.

**Comment by csperando** [comment]
Please delete this issue. A junior dev was supposedly logged into our organization's account on accident, and has since been shown how to contribute to open source projects. Sorry for the inconvenience.
