### ISSUE TITLE
h2 style

### ISSUE THREAD

**Issue by KamasamaK** [foundeo/cfdocs#1496]
I assume it was added for a reason, but would it be fine to remove `text-transform: uppercase` from `h2` rules? I think headings look fine without that rule, and guides like [ColdFusion Java System Properties](https://cfdocs.org/system-properties#coldfusion-java-system-properties) have headings that just look wrong.

**Comment by pfreitag** [comment]
The headings like Examples, Compatibility are uppercased on the primary doc page style, but I agree it looks pretty bad in the guides there... I'm ok with removing it.
