### ISSUE TITLE
Missing Lucee's IsInThread method

### ISSUE THREAD

**Issue by michaelborn** [foundeo/cfdocs#1521]
## IsInThread

> Determines whether the executing code is inside a cfthread or not.

(This appears to be a Lucee-only method.)

https://docs.lucee.org/reference/functions/isinthread.html

**Comment by D-Anir** [comment]
Hi, can you assign this issue to me if it is still open?

**Comment by pfreitag** [comment]
go for it

**Comment by cybersonic** [comment]
Added a Pull Request for this issue: https://github.com/foundeo/cfdocs/pull/1678
