### ISSUE TITLE
Broken link last line in README for `http://cfeclipse.org/`

### ISSUE THREAD

**Issue by jbampton** [foundeo/cfdocs#1528]
Website is showing an error:

<img width="643" alt="Screen Shot 2022-09-17 at 1 33 48 am" src="https://user-images.githubusercontent.com/418747/190676894-cf06db8e-4a46-4ba4-b806-25abf28b6b04.png">

**Comment by pfreitag** [comment]
@jbampton - ok, thanks - we can remove that link in the readme
