### ISSUE TITLE
Decision Functions - not synced with github

### ISSUE THREAD

**Issue by pczarn2** [foundeo/cfdocs#1599]
@pfreitag Looks like isDateObject is not showing up on the decision functions page, even though the change have been merged to master few days ago with Pull Request #1589

**Comment by pfreitag** [comment]
@pczarn2 I am seeing it - it is either still cached at the edge server in your region, or by your browser, give it some time and it will show up.

**Comment by pczarn2** [comment]
@pfreitag got it!
