### ISSUE TITLE
list of functions not populated from individual pages

### ISSUE THREAD

**Issue by stelt** [foundeo/cfdocs#161]
For example http://cfdocs.org/decision-functions having "requist"

**Comment by pfreitag** [comment]
Thanks I see that it lists isSoapReqiest which is a typo and needs to be fixed.

**Comment by pfreitag** [comment]
Probably should have a unit test that double checks this stuff for us.

**Comment by stelt** [comment]
"Fork on Github" gives me a 404, not too surprisingly

**Comment by pfreitag** [comment]
This was fixed by @maryjos including the fork link.

**Comment by maryjos** [comment]
I updated the list manually, not sure there's any way to do this automatically

**Comment by pfreitag** [comment]
No there is no way to build the category list automatically, they are human defined categories - I could add a unit test to make sure there are no typos however.
