### ISSUE TITLE
isValid

### ISSUE THREAD

**Issue by rayvarner** [foundeo/cfdocs#1628]
isValid type option:

Docs should be updated to reflect that function/closure is an option for 'type'. 
I don't know if this is undocumented but it works in ACF and Lucee.

**Function** works in ACF and Lucee:
`isValid( "function", function(a,b) {return a+b;} );`

**Closure** only works for Lucee:
`isValid( "closure", function(a,b) {return a+b;} );`

**Comment by pfreitag** [comment]
cool, would be good to see if we can figure out what version of ACF/Lucee these were added to as well.

**Comment by pfreitag** [comment]
hmm - `function` is listed in ACF's docs already, and I tested it on trycf all engines seem to support it going back to Railo 4.2 and CF10 - so for that one I think it might have been there since CF7 and we just missed it.

**Comment by rayvarner** [comment]
Thanks for responding Pete. I'll try to get involved more with cfdocs;
especially since they're THE best reference.

If you ever need a remote developer let me know. Thanks!

Ray
http://www.linkedin.com/in/raymondvarner
