### ISSUE TITLE
Missing 'GetSystemSetting' function

### ISSUE THREAD

**Issue by orcpac7** [foundeo/cfdocs#1656]
Searched for the function "GetSystemSetting" and didn't find it. Tried both by appending to url: "https://cfdocs.org/getsystemsetting", searching using the "tag or function" textbox, and reviewing the function at "https://cfdocs.org/all"
Here's what CoPilot had to say:
The GetSystemSetting function in ColdFusion is used to retrieve system-level settings or configuration values. These settings are typically defined in the ColdFusion Administrator or in configuration files. Here are some details about the GetSystemSetting function:

Purpose: Retrieves system-level settings or configuration values.
Usage: GetSystemSetting(settingName)
Parameters:
settingName: The name of the system setting you want to retrieve.

**Comment by KamasamaK** [comment]
From what I can find, that is not a function in ColdFusion or Lucee. It seems like it might be a function added by ColdBox.

**Comment by pfreitag** [comment]
@orcpac7 I checked using getFunctionList() https://trycf.com/gist/e040ef96068ad8fa0e5ba5eebf1d5b50/acf2023 as well. We are only going to document built in functions (BIF's) here, you should be able to find docs for that on ColdBox here: https://coldbox.ortusbooks.com/getting-started/configuration/coldbox.cfc/system-settings-java-properties-and-environment-variables 

thanks for confirming that as well @KamasamaK going to close this issue.
