### ISSUE TITLE
Possible change of font due to capital i being nigh on the same as a lower case l

### ISSUE THREAD

**Issue by chopki** [foundeo/cfdocs#166]
Example on this page http://cfdocs.org/lsiscurrency. Its not 100% clear on first glance if the function is called **i**s**L**sCurrency or **L**s**i**sCurrency.

I do get though that this is a generall issue with a lot of fonts.

**Comment by pfreitag** [comment]
Yes good call -- I will have to find a good replacement font that differentiates better

**Comment by pfreitag** [comment]
It will take some time for the caches to update, but it has been fixed.
