### ISSUE TITLE
CFMail needs work

### ISSUE THREAD

**Issue by pfreitag** [foundeo/cfdocs#225]
It is missing the new attributes added in CF11.

It could also use an example showing how to send using a query.

**Comment by mjhagen** [comment]
Should the script syntax using the mail.cfc method maybe be moved to it's own page/section? I'll upload what I have now (#257), which is mostly just cleanup and some fixes. But I'll continue working on it and create some examples (for query usage like you mentioned)

**Comment by pfreitag** [comment]
I think it is ok to have that on the cfmail page, there is no better place for it right now. 

Thanks for updating it!
