### ISSUE TITLE
CFImage tag needs examples and some updates.

### ISSUE THREAD

**Issue by pfreitag** [foundeo/cfdocs#226]
Needs examples resize would be a good first example. 
Needs min_version:8 
Missing Attribute: interpolation CF10+ applies to action = "resize"

**Comment by mjhagen** [comment]
Is anyone working on this one? If not, I'd like to take a stab at it.

**Comment by pfreitag** [comment]
Nope -- no one is working on it, feel free to tackle it

**Comment by mjhagen** [comment]
Alright, submitted PR #253 with basic examples, maybe there should be a recommendation in there that points to the image*() functions?

**Comment by pfreitag** [comment]
Thanks for all the examples...

I added some of the image functions to the `related` key in the json file, and I also linked to the Image Functions category in the links area.
