### ISSUE TITLE
CFFTP add attribute 'systemtype'

### ISSUE THREAD

**Issue by mjhagen** [foundeo/cfdocs#269]
As posted to Slack by @brandner:

> Documentation for CFFTP attribute 'systemtype' should be added (ACF at least). Just spent an hour on that rabbit hole. As per Pavan Kumar - http://cfpavankumar.blogspot.ca/2015/07/cfftp-listdir-fails-when-syst-command.html

**Comment by pfreitag** [comment]
From the blog entry:

>A new attribute has been added to CFFTP tag called systemType which specifies how to parse the file > list response without invoking SYST command. This attribute is available from CF11 update 3.

> Possible values for the attribute are (The same values are also applicable for the JVM flag)
> `WINDOWS`: if specified CFFTP treats the response as Windows-Style directory listing
> `UNIX`:  if specified CFFTP treats the response as Unix-Style directory listing 
> Also, can specify any class name which implements `org.apache.commons.net.ftp.FTPFileEntryParser`
