### ISSUE TITLE
Add id attributes to the examples

### ISSUE THREAD

**Issue by mjhagen** [foundeo/cfdocs#278]
So you can link to them directly like so: https://cfdocs.org/cfmail#ex4

**Comment by pfreitag** [comment]
Good suggestion, this is done - it may take some time for it to show up on the live site...

Keep in mind that the id is based on the array index so if someone moved examples into a different order it would possibly point to another example.

**Comment by pfreitag** [comment]
Also btw you can link https://cfdocs.org/cfmail#examples that was already working previously.

**Comment by mjhagen** [comment]
:+1:
