### ISSUE TITLE
CF2016 queryEach

### ISSUE THREAD

**Issue by pfreitag** [foundeo/cfdocs#289]
https://helpx.adobe.com/content/help/en/coldfusion/cfml-reference/coldfusion-functions/functions-m-r/queryeach.html

**Comment by shaedrich** [comment]
Refers to #572

**Comment by shaedrich** [comment]
@pfreitag Could be closed now.

**Comment by pfreitag** [comment]
Thanks!

**Comment by shaedrich** [comment]
You're welcome!
