### ISSUE TITLE
CF2016 Updated timeFormat and dateFormat

### ISSUE THREAD

**Issue by pfreitag** [foundeo/cfdocs#306]
TimeFormat added masks for timezone: 

`z`: Time zone in literal format, for example, GMT
`Z`: Time zone in hours of offset (RFC 822 TimeZone), for example, +0530
`X`: Time zone in hours of offset in ISO 8601 format `X: +05`  `XX: +0530` `XXX: +05:30`

**Comment by pfreitag** [comment]
Also added these masks to `dateFormat` -- it is not listed/documented but my guess/hope is that `dateTimeFormat` also support these masks.

**Comment by shawnoden** [comment]
Support for masking is kinda wonky between dateFormat(), timeFormat() and dateTimeFormat(). I think dateTimeFormat() follows Java's SmallDateTime masking, while dateFormat() doesn't. "Y" and "y" are slightly different in dateTimeFormat() but the same in dateFormat().
