### ISSUE TITLE
fileUpload

### ISSUE THREAD

**Issue by henrylearn2rock** [foundeo/cfdocs#318]
I believe, new for CF10, there's a 5th argument for fileUpload() that define if Strict is true (default) or false.

**Comment by mjhagen** [comment]
There is, but I've not found it in the Adobe (or Lucee) docs, do you have more info on it?

**Comment by henrylearn2rock** [comment]
Unfortunately I can't. That's why I hope this doc can include it at least

**Comment by henrylearn2rock** [comment]
Thanks!
