### ISSUE TITLE
cfprocessingdirective not implemented in cfscript

### ISSUE THREAD

**Issue by infernocloud** [foundeo/cfdocs#331]
It looks like cfprocessingdirective is not actually implemented in cfscript in Adobe Coldfusion.
https://bugbase.adobe.com/index.cfm?event=bug&id=3712167

**Comment by mjhagen** [comment]
It is in Lucee, @pfreitag how have you solved that for other non-ACF tags-in-script?

**Comment by pfreitag** [comment]
I think putting something under notes in the engine key for ACF stating: `Not currently implemented in CF11 / CF 2016 in script (bug 3712167)` would do the trick.
