### ISSUE TITLE
dateCompare - valid Dateparts

### ISSUE THREAD

**Issue by chopki** [foundeo/cfdocs#347]
Unsure if all the dateparts are valid: Q, Y, W and L  do not appear on any of the official documentation sites and do not work in CF2016 - tryCF.com currently having issues testing lucee so i cannot check quickly.

Either need to add version specific tags for the specific datepart values or remove if they do not work on any.

Lucee 4.5 http://docs.lucee.org/reference/functions/datecompare.html
CF2016 https://helpx.adobe.com/coldfusion/cfml-reference/coldfusion-functions/functions-c-d/DateCompare.html

**Comment by pfreitag** [comment]
For Lucee 4.5.2 it says valid dateparts are: `s,n,h,d,m,y,yyyy`

**Comment by pfreitag** [comment]
I am updating cfdocs for this, thanks for pointing out the issue.
