### ISSUE TITLE
structmap and listmap functions missing lucee support

### ISSUE THREAD

**Issue by ryanguill** [foundeo/cfdocs#356]
The following functions say (incorrectly) that they are not supported on lucee

* http://cfdocs.org/structmap ↝ http://docs.lucee.org/reference/functions/structmap.html
* http://cfdocs.org/listmap ↝ http://docs.lucee.org/reference/functions/listmap.html

`querymap` says it isnt supported by ACF but it is, but I think there is already an issue for that.

**Comment by atuttle** [comment]
Sorry for multiple PR's to fix this one issue -- I just edit directly on github and it's easier to do it this way. :)

**Comment by pfreitag** [comment]
No problem @atuttle whatever works for you - thanks for fixing!

**Comment by ryanguill** [comment]
yes, thanks @atuttle! 💯
