### ISSUE TITLE
cfinput 'validateAt' not supported in Lucee

### ISSUE THREAD

**Issue by mborn319** [foundeo/cfdocs#365]
This should be at least mentioned at http://cfdocs.org/cfinput.

http://pastebin.com/MMKW1kc5
https://github.com/getrailo/railo/wiki/CFML-tags-that-are-not-supported

**Comment by pfreitag** [comment]
Are you sure? `validateAt` is listed as an attribute on the Lucee doc page: http://docs.lucee.org/reference/tags/input.html

**Comment by mborn319** [comment]
I'm getting `attribute validateAt is not supportrd for tag input` on a Lucee installation.
http://benefitdg.brockettcreative.com/cfinput.cfm

**Comment by pfreitag** [comment]
Thanks for double checking for me! Fixed it.
