### ISSUE TITLE
Running code example's causing errors

### ISSUE THREAD

**Issue by clang676** [foundeo/cfdocs#371]
While trying to run the sample code through different examples and browsers i keep getting the error message " Oh snap-Looks like someone is hogging all the resources. Click run again and we'll try another server." I'm Current Engine:  Adobe cold fusion 2016, i have tried down grading and still get this error.

Two console errors: 
--`Mixed Content: The page at 'https://cfdocs.org/cjustify' was loaded over HTTPS, but requested an insecure form action 'http://acf12-sbx.trycf.com/getremote.cfm'. This request has been blocked; the content must be served over HTTPS.`

--`jquery.js:8698 Mixed Content: The page at 'https://cfdocs.org/cjustify' was loaded over HTTPS, but requested an insecure script 'http://acf12-sbx.trycf.com/getremote.cfm?callback=jQuery2140733773374724760…F9642D8C1467816587145-748e4cdb-12df-1cfd-851b-28cef8178d56&_=1467816587009'. This request has been blocked; the content must be served over HTTPS.`

**Comment by mjhagen** [comment]
@clang676, The examples are run using trycf.com, which doesn't yet run on https. If you go through http://cfdocs.org/cjustify you should be able to run the example.

@foundeo, perhaps not show the Run Code button when visiting through https?

**Comment by clang676** [comment]
@mjhagen Thanks that makes sense, i would agree with you to hide the "Run Code" button when viewing the website though https

**Comment by pfreitag** [comment]
@clang676 you should get a javascript alert when you click Run Code over HTTPS that explains the issue. Did you get that on your browser?

For browsers that do not block mixed content (older browsers) the examples will still work, so that is why it is not hidden all together. Hopefully trycf will add https soon so it will just work.

**Comment by mjhagen** [comment]
Yeah I was wondering about that alert too. I did get it.

**Comment by pfreitag** [comment]
This was fixed a while ago, as trycf now does support https. Forgot to close the issue...
