### ISSUE TITLE
cfwebsocket sub-channel example

### ISSUE THREAD

**Issue by sjmjustin** [foundeo/cfdocs#381]
In the example on sub-channels, the sub-channel applies to the channel being subscribed to (e.g. the subscribeTo attribute or subscribe() JavaScript method).  The example implies that the sub-channel is specified in the name attribute which is not correct (name is the the JavaScript object that will be created).

**Comment by pfreitag** [comment]
Thanks @sjmjustin for reporting this. Can you suggest a better example? If so you can either post it here and I'll update it, or you can submit a pull request which makes it super easy for me.

**Comment by pfreitag** [comment]
Fixed in PR #398
