### ISSUE TITLE
[Enhancement] Embeding, or linking to, TryCF.com ScratchPad

### ISSUE THREAD

**Issue by CreativeNotice** [foundeo/cfdocs#40]
We'd have to contact the fellow who runs trycf.com, but it would be cool if we could define a new item in our json object like: "example_gist":"gist url here" and either have the ScratchPad load the gist in cfdocs or at least link to trycf.com and load the gist content there.

The latter could be implemented very easily I think since he's already allowing users to load a gist on trycf.com. The former would be super convenient.

Probably want to store these gists in a central account so none go missing.

**Comment by pfreitag** [comment]
This is done.
