### ISSUE TITLE
fileDelete

### ISSUE THREAD

**Issue by sfeldkamp** [foundeo/cfdocs#400]
fileDelete throws an error if the file doesn't exist.  I think this out to be mentioned somewhere in the documentation.  I'm happy to update it myself, but I didn't see in the json structure a place to define what exceptions a function may throw.

Should I just add it to the description?  Or should it be left out of the documentation?

**Comment by pfreitag** [comment]
Hi Seth - there is nothing in the structure to document what a function or tag throws, that might be a good addition someday, but for now if you would like to update the description that would be much appreciated!

**Comment by pfreitag** [comment]
@sfeldkamp are you still up for adding this to the description? If so just go here: https://github.com/foundeo/cfdocs/edit/master/data/en/filedelete.json and update it.

**Comment by caramelomartins** [comment]
@pfreitag I can update this description if you so wish.

**Comment by caramelomartins** [comment]
PR #436 fixes this.
