### ISSUE TITLE
Lucee: Attribute 'key' is not allowed for tag cfftp

### ISSUE THREAD

**Issue by ianosullivan** [foundeo/cfdocs#401]
Cannot use public_key FTP type with Lucee. Error returned is 'Attribute key is not allowed for tag cfftp'

**Comment by pfreitag** [comment]
I updated the engine notes to include this... You might want to file a bug with lucee or check to see if there is one already. If you do, post the link back here.

**Comment by ianosullivan** [comment]
Thanks Pete.
Bug added here - https://luceeserver.atlassian.net/browse/LDEV-1003
Ian.
