### ISSUE TITLE
listEach

### ISSUE THREAD

**Issue by philcruz** [foundeo/cfdocs#430]
The example of list.each()

```
list = "a;b;c";
list.each(function(element,index,list) { 
    writeOutput("#index#:#element#;");
}, ";");
```
doesn't work on ACF11

**Comment by pfreitag** [comment]
Thanks for reporting this @philcruz it looks like for ACF11 you need to use `list.listEach()` instead of `list.each()` which only works on Lucee. The `listEach` member function appears to work on Lucee 4.5+ and CF11+
