### ISSUE TITLE
Missing Functions - todo.cfm

### ISSUE THREAD

**Issue by caramelomartins** [foundeo/cfdocs#432]
Hello,

I have noticed something odd. If I go to http://cfdocs.org/reports/todo.cfm, all functions are documented but a list of strings appears in the top of the website. 

Is this expected behaviour? I can try to have a look at it.

Thanks,
Hugo

**Comment by caramelomartins** [comment]
Hello,

Any news regarding this situation?

Thanks,
Hugo

**Comment by pfreitag** [comment]
Hi @caramelomartins sorry I didn't see this ticket, I just fixed the issue

**Comment by caramelomartins** [comment]
Hi @pfreitag, that's OK. I couldn't assign it to myself and since you didn't reply I didn't work on it...maybe I should have.

Either way, I'm glad it is fixed.
