### ISSUE TITLE
listLen (CF10+) has a "includeEmptyValues"

### ISSUE THREAD

**Issue by JamoCA** [foundeo/cfdocs#446]
An optional true/false "includeEmptyValues" parameter was added in ColdFusion 10.

It's listed on the official [Adobe CF documention](https://helpx.adobe.com/coldfusion/cfml-reference/coldfusion-functions/functions-l/listlen.html).  (They weren't consistent and indicated that it wasn't added until CF10.)

**Comment by pfreitag** [comment]
Thanks for adding this @JamoCA 

If you want to take a stab at fixing this yourself you can go here: https://github.com/foundeo/cfdocs/blob/master/data/en/listlen.json and click the Edit pencil and add the argument under `params`
