### ISSUE TITLE
Calling all contributors...

### ISSUE THREAD

**Issue by atuttle** [foundeo/cfdocs#447]
@CraicOverflow89 @ianosullivan @shawnoden @mborn319 @jeremyhalliwell @rossmd @laurencehoess @mjclemente @wilgeno @scottsteinbeck @Miguel-F @egomezm @redtopia @Jimcumming @aaronstoddard @spills @phils @MattMS @kenguest @gratzc @bsdlp @trentrichardson @osmanzeki @sjmjustin @invalid-email-address @bferdinandus @KrunchMuffin @martypaz @petrichor8 @ryandeba @simonbingham @Prefinem @chopki @bdw429s @GiancarloGomez @gpickin @boyzoid @MikeBurt @abramadams @awayken @nueffl @caramelomartins @evagoras @adamcameron @dhjones64 @sihu @rayfaddis @cfvonner @aliaspooryorik @steltenpower @nikhildevre @oldAndBold @cfmitrah @murphydan @bmdoherty @Twillen @derrick13 @elpete @CreativeNotice @tomchiverton @yogidevbear @jcberquist @neokoenig @ryanguill @maryjos @mjhagen @ddspringle @penhorwood @fmdano @pfreitag

Apologies for the odd approach to getting in touch! 

Some of you I'm sure I have contact information for, but for most of you I do not. As a token of my gratitude for your contributions to a project for which I hold great admiration, I wanted to offer you a free copy of [my book](http://restassuredbook.com/), no strings attached! Just email me: adamtuttlecodes@gmail.com and I'll happily reply with a 100% off discount code.

I know that some of you have already purchased a copy of my book. For that you have my unending thanks, and in lieu of this gift I offer you this digital high five: ✋🏻 Thanks for being awesome.

Happy holidays, everyone!

**Comment by atuttle** [comment]
Looks like github has a limit on the number of people you can tag in a single comment. I'll have to try the rest separately. Hope this works...

@nikhildevre @oldAndBold @cfmitrah @murphydan @bmdoherty @Twillen @derrick13 @elpete @CreativeNotice @tomchiverton @yogidevbear @jcberquist @neokoenig @ryanguill @maryjos @mjhagen @ddspringle @penhorwood @fmdano @pfreitag

**Comment by pfreitag** [comment]
Very Generous of you Adam -- thanks & Merry Christmas / Happy Holidays!

**Comment by ddspringle** [comment]
Ditto what Pete said. Thank you Adam. I'm working on a Taffy API right now so this will come in quite handy :100:

**Comment by cfvonner** [comment]
Thank you Adam! That's very generous.

**Comment by cfmitrah** [comment]
Thanks a lot @atuttle

**Comment by AdspurAndrew** [comment]
That's amazing! Thank you Adam :)

**Comment by simonbingham** [comment]
I already have a copy, but thanks for the offer Adam.

**Comment by Miguel-F** [comment]
Thanks Adam this is very kind of you.  Happy Holidays!!!!

**Comment by chopki** [comment]
Thanks Adam. Awesome gift.

**Comment by pfreitag** [comment]
Going to close this issue, thanks again Adam for your generous offer.
