### ISSUE TITLE
Problems with CFHTMLTOPDF

### ISSUE THREAD

**Issue by ifocusdata** [foundeo/cfdocs#47]
Just trying this tag for the first time in a trial version of CF 11.  I'm unable to pass any URL vars with the source without error, for both .cfm and .html pages.  For example, source="myPage.html" works as expected, but source="myPage.html?x=1" throws a 500 error.

When the urltoken is not passed with the source when the source is a .cfm page, the session (login) is not recognized and we get thrown to the login page.

**Comment by wboka** [comment]
This issue appears to have been resolved over on the Adobe site: https://forums.adobe.com/thread/1488218?start=0&tstart=0
