### ISSUE TITLE
Better/more clear navigation on larger pages

### ISSUE THREAD

**Issue by shaedrich** [foundeo/cfdocs#504]
On larger pages you have to scroll much to and fro. In my opinion this could be improved.
* Should there be a table of contents for longer pages?
* Should the sections be expandable/collapsable?
* Should there be tabs for cfml and cfscript syntax examples?

**Comment by pfreitag** [comment]
Expandable/Collapsable sections would probably be the easiest way to accomplish this... 

I'm afraid adding a TOC or tabs for cfml vs cfscript might complicate the UI too much, want to keep it simple and clean.

**Comment by shaedrich** [comment]
Okay, Expandable/Collapsable sections would be a step in the right direction.

But how to handle many cfml/cfscript examples alternating with one another?

**Comment by shaedrich** [comment]
Should/could I add pure css expand/collapse?
