### ISSUE TITLE
DateTime type

### ISSUE THREAD

**Issue by KamasamaK** [foundeo/cfdocs#511]
As far as I am aware, there is only one date type in CFML. Even though it is actually a datetime, the proper name of the data type is `date`. Should all types marked as "DateTime" actually be "Date"?

This was prompted by a [recent commit](https://github.com/foundeo/cfdocs/commit/87dcb922a38648b37a292b148fbefb8611ae4d68) by @pfreitag that changed "DateTime" to "Date".

**Comment by pfreitag** [comment]
@KamasamaK - yeah, I saw that today as well - they should be marked as `date` IMHO since that is the `type` you would specify in `cfargument` `cfparam` etc.

So if you see any `DateTime` feel free to fix them.

**Comment by shaedrich** [comment]
Pull Request: #520

**Comment by pfreitag** [comment]
Fixed via #520
