### ISSUE TITLE
Closure type

### ISSUE THREAD

**Issue by KamasamaK** [foundeo/cfdocs#521]
I've noticed some params such as one in [`arrayEach`](https://cfdocs.org/arrayeach) that has a type of `Closure`. The [Lucee docs](http://docs.lucee.org/reference/functions/arrayeach.html) use the type `function`. ACF appears to only use `function` as the type name (see [`returnType` in `cffunction`](https://helpx.adobe.com/coldfusion/cfml-reference/coldfusion-tags/tags-f/cffunction.html) and [`type` in `cfargument`](https://helpx.adobe.com/coldfusion/cfml-reference/coldfusion-tags/tags-a-b/cfargument.html)), but also refers to them as closures in some places even naming the validation function `isClosure`. Ultimately, I think it should be `function` to match the type name in ACF.

**Comment by pfreitag** [comment]
Yes, I think `function` is the appropriate type name to use here.
