### ISSUE TITLE
Add label for Railo

### ISSUE THREAD

**Issue by shaedrich** [foundeo/cfdocs#524]
There are currently labels for CF, Lucee and BD. There should be one for Railo as well or is there already one which is just not shown here for some reason in [`dateTimeFormat`](https://github.com/foundeo/cfdocs/tree/master/data/en/datetimeformat.json#L17): https://cfdocs.org/datetimeformat

**Comment by pfreitag** [comment]
Yeah - it is just not shown. It used to be there, but  I removed Railo in favor of Lucee since Railo was basically abandoned.

**Comment by shaedrich** [comment]
So Railo should be removed from `engines`?

**Comment by pfreitag** [comment]
I don't think it should be removed from engines where it exists, someone might find the version data in there useful. I just would not add a key for railo going forward to engines if you are adding a new tag / function.

**Comment by shaedrich** [comment]
Okay.
