### ISSUE TITLE
Edit auto-generated files

### ISSUE THREAD

**Issue by shaedrich** [foundeo/cfdocs#536]
Is it wise to make auto-generated files like [CF11](/foundeo/cfdocs/blob/master/data/en/cf11.json) be editable?

**Comment by pfreitag** [comment]
I think its useful to have them in the repository for anyone that is using the json files. I monitor the pull requests pretty closely so I would take not if someone modified one of them.

**Comment by shaedrich** [comment]
I meant rather the 'Edit' button on cfdocs.

**Comment by pfreitag** [comment]
Ah... good call, yeah that should be removed then.

**Comment by shaedrich** [comment]
Is that only needed for the versions or for all (`tags`,`functions`,`guides`,`all`,`categories`)?

**Comment by pfreitag** [comment]
Yeah, anything that is auto generated by the indexer does not need to have an edit button.

**Comment by shaedrich** [comment]
@pfreitag Due to #537 this issue can be closed, coudn't it?
