### ISSUE TITLE
ColdFusion https error - cfdocs not accessible (show stopper)

### ISSUE THREAD

**Issue by shaedrich** [foundeo/cfdocs#550]
Invalid CFML construct found on line 34 at column 164.
--
ColdFusion was looking at the following text:

https

The CFML compiler was processing:

* A cfset tag beginning on line 34, column 10.
* A cfset tag beginning on line 34, column 10.

URL: https://cfdocs.org/queries

**Comment by pfreitag** [comment]
was caused by #548 - I reverted that PR.
