### ISSUE TITLE
Display number of issues for function or tag

### ISSUE THREAD

**Issue by shaedrich** [foundeo/cfdocs#562]
Next to the `edit` button on cfdocs is the `issue` button where you can create a new issue. Currently we have more than one issue page and you have to scroll up and down to find a suitable 'project' to solve or improve.

It would be nice to split the button into something like "[`(5) issues`](https://github.com/foundeo/cfdocs/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20cfloop)" and "[`+ issue`](https://github.com/foundeo/cfdocs/issues/new?title=cfloop)". Is there a way to find out the number of issues concerning a specific function or tag? Than we could link to the filtered issues as I linked them. So you can

* Edit the tag or function
* Nag that there is something wrong/Discuss an improvement proposal
* Get a read where to contribute to improve this tag or function

**Comment by pfreitag** [comment]
It is possible: https://api.github.com/search/issues?q=is:open+repo:foundeo/cfdocs+cfloop

**Comment by shaedrich** [comment]
Silly me! Of course it is!

Do you agree with me that we could implement this?

**Comment by pfreitag** [comment]
I think it would be cool... my only concern is that the content is cached for 1 week by default so it might get stale. I wonder if it can be implemented in JS? - depends if github allows CORS on their api calls.

**Comment by shaedrich** [comment]
They do. So it can be done this way 👍
