### ISSUE TITLE
setMetadata member function

### ISSUE THREAD

**Issue by shaedrich** [foundeo/cfdocs#604]
Shouldn't there be a separate `setMetadata()` member function doc as mentioned in [serializeJSON](http://cfdocs.org/serializejson)?

https://github.com/foundeo/cfdocs/blob/ad46f496f93b97d25e48f713eb0ca4516e95b459/data/en/serializejson.json#L50-L55

**Comment by pfreitag** [comment]
Fixed in #866 - thanks everyone!
