### ISSUE TITLE
[MAJOR] Fix TravisCI build stopper

### ISSUE THREAD

**Issue by shaedrich** [foundeo/cfdocs#675]
TravisCI checks always fail causing this error:
> CommandBox 3.8.0+00766
> install
> Installing package [forgebox:testbox@2.5.0]
> Verifying package 'testbox' in ForgeBox, please wait...
> Aww man, ForgeBox isn't feeling well.
> Uh-oh, ForgeBox returned something other than JSON. Run "system-log | open" to see the full response. GET https://www.forgebox.io/api/v1/entry/testbox
> 523 Origin Unreachable
> We're going to look in your local artifacts cache and see if one of those versions will work.
> No satisfying version found for [2.5.0]. Well, we tried as hard as we can. ForgeBox is unreachable and you don't have a usable version in your local artifacts cache. Please try another version.
> server start cfengine=adobe@2016 port=8123 JVMArgs="-Djava.security.egd=file:/dev/./urandom" openbrowser=false
> Contacting ForgeBox to determine the latest & greatest version of [adobe 2016]... Use an exact 'cfengine' version to skip this check.
> Aww man, ForgeBox isn't feeling well.
> Uh-oh, ForgeBox returned something other than JSON. Run "system-log | open" to see the full response. GET https://www.forgebox.io/api/v1/entry/adobe
> 523 Origin Unreachable
> We're going to look in your local artifacts cache and see if one of those versions will work.
> Error executing command server start cfengine=adobe@2016 port=8123 JVMArgs="-Djava.security.egd=file:/dev/./urandom" openbrowser=false, exiting recipe.
> ERROR (3.8.0+00766)
> No satisfying version found for [2016].
> Well, we tried as hard as we can. ForgeBox is unreachable and you don't have a usable version in your local artifacts cache. Please try another version.
> No satisfying version found for [2016].
> [(Source)](https://travis-ci.org/foundeo/cfdocs/jobs/292712327#L467-L494)

**Comment by pfreitag** [comment]
Was due to an issue with forgebox - works now

**Comment by shaedrich** [comment]
Thanks.
