### ISSUE TITLE
url.name is evaluated to "404"

### ISSUE THREAD

**Issue by shaedrich** [foundeo/cfdocs#683]
On 404 page the name of the requested but not found doc should be passed to the link for creating a new doc file on GitHub. If you check the link, you'll notice that "404" is passed in instead.

https://github.com/foundeo/cfdocs/blob/17cb9eb908ac29c4ea83b4d98676b08d6c674668/doc.cfm#L36

Why did that go wrong and do you have an idea to solve this?

**Comment by shaedrich** [comment]
Do you really think, this is better?

**Comment by pfreitag** [comment]
Yeah I think for you or me or someone else who is a regular contributor it makes sense to have it go to an empty file, but for everyone else the will not know what to do with the empty text box.

**Comment by shaedrich** [comment]
So they have to be leaded to [CONTRIBUTING.md](/foundeo/cfdocs/blob/master/CONTRIBUTING.md)...

**Comment by pfreitag** [comment]
I don't know if most users will be motived to actually contribute the docs, getting them to at least report a missing doc would be good.

**Comment by shaedrich** [comment]
They could decide it, don't you think, that would be good?
