### ISSUE TITLE
cfquery

### ISSUE THREAD

**Issue by qlp-developers** [foundeo/cfdocs#701]
One small part of the "result" attribute reference is documented incorrectly.

* ColumnList: Column list, comma seperated. (numeric)

Should actually read:

* ColumnList: Column list, comma separated. (string/list)

**Comment by shaedrich** [comment]
String is right. Fixed this in #702.

**Comment by pfreitag** [comment]
Thanks for reporting this @qlp-developers and thanks for fixing it @shaedrich 

The change has been merged.
