### ISSUE TITLE
cfexecute

### ISSUE THREAD

**Issue by aplewak** [foundeo/cfdocs#772]
What version was the cf script developed. I keep getting cfexecute undefined variable

**Comment by pfreitag** [comment]
I haven't tested it but CF11 implemented most of the script to tag stuff. What version are you trying it on?

**Comment by aplewak** [comment]
currently on CF10

**Comment by pfreitag** [comment]
Yeah you would need CF11 for the `cfexecute(...)` syntax.

**Comment by aplewak** [comment]
Ah, I didn't see the tool-tip before that explains the versioning.

Thanks
