### ISSUE TITLE
Missing Struct Array Metadata functions

### ISSUE THREAD

**Issue by shaedrich** [foundeo/cfdocs#782]
Adobe docs: https://helpx.adobe.com/coldfusion/cfml-reference/coldfusion-functions/functions-s/structsetmetadata.html
Added in: https://helpx.adobe.com/coldfusion/kb/coldfusion-2016-update-2.html

Fixes #604

**Comment by KamasamaK** [comment]
That update also included other new metadata functions: [`structGetMetadata`](https://helpx.adobe.com/coldfusion/cfml-reference/coldfusion-functions/functions-s/structgetmetadata.html), [`arrayGetMetadata`](https://helpx.adobe.com/coldfusion/cfml-reference/coldfusion-functions/functions-a-b/arraygetmetadata.html), and [`arraySetMetaData`](https://helpx.adobe.com/coldfusion/cfml-reference/coldfusion-functions/functions-a-b/arraysetmetadata.html).

**Comment by pfreitag** [comment]
Fixed in #866 - thanks everyone!

**Comment by KamasamaK** [comment]
@pfreitag Did you want me to make one or three more issues? It made sense to me to have them all together since they are so closely related.

**Comment by pfreitag** [comment]
@KamasamaK no - I'll reopen this one
