### ISSUE TITLE
Reports

### ISSUE THREAD

**Issue by shaedrich** [foundeo/cfdocs#794]
Why does [Missing Version Number](https://cfdocs.org/reports/missing-version.cfm) differ from [Missing Related links](https://cfdocs.org/reports/missing-related.cfm)? All the others share the [same script](/foundeo/cfdocs/tree/master/reports/missing-layout.cfm).

**Comment by pfreitag** [comment]
No reason that I know of.

**Comment by shaedrich** [comment]
So "Missing Version Number" content can be made consistent?
