### ISSUE TITLE
Polyfills

### ISSUE THREAD

**Issue by shaedrich** [foundeo/cfdocs#812]
Would it be a good idea to provide polyfills for engine versions without support for a specific function or tag?

To migrate this, we could use [these overrides](https://gist.github.com/anonymous/490abe8522804f754dbf3456efdc7d54) from [watney](/ryanguill/watney/) by [@ryanguill](/ryanguill).

**Comment by pfreitag** [comment]
I think these could be added as examples

**Comment by shaedrich** [comment]
To easier distinguish polyfills from examples, "code sections" could be tagged. There are probably more types than just "example" or "polyfill":
* sample usage
* polyfill
* exceptions
* configuration
* etc.

That could also help with grouping, sorting and perhaps hiding "code sections"
