### ISSUE TITLE
trace arguments are given in the wrong (non-ACF) order

### ISSUE THREAD

**Issue by displague** [foundeo/cfdocs#848]
The `trace` arguments are given in the wrong (non-ACF) order:

https://helpx.adobe.com/coldfusion/cfml-reference/coldfusion-functions/functions-t-z/trace.html
```
trace (var, text, type, category, inline, abort)
```

https://cfdocs.org/trace
```
 trace([abort] [, category] [, inline] [, text] [, type] [, var]) → returns void 
```

I attempted to use the CFDocs order and received a warning that the value supplied to `inline` was not a simple type that could be converted to boolean.

---
This was likely copied from https://helpx.adobe.com/coldfusion/cfml-reference/coldfusion-tags/tags-t/cftrace.html which lists the arguments in alphabetical order.

**Comment by pfreitag** [comment]
Thanks for reporting this @displague we'll get that fixed!

**Comment by displague** [comment]
> 	"coldfusion": {"minimum_version":"9", "notes":"As of CF11 parameters must be comma seperated.", "docs":"https://helpx.adobe.com/coldfusion/cfml-reference/coldfusion-functions/functions-t-z/trace.html"}, 

I don't think that is the case.  In CF11, while I was debugging the problem, I specified all of the argument names in the old cfdocs order, and it worked fine: 
```
trace(abort=false, category="x",inline=false, text="words", type="error", var="varname")
```
