### ISSUE TITLE
Improve duplicate() example

### ISSUE THREAD

**Issue by jinglesthula** [foundeo/cfdocs#853]
I'll see if I can put together a PR when I get time, but wanted to note that the example on the `duplicate()` page doesn't really demonstrate that the original is untouched, as `replace()` returns a different string anyway.

You can say `myNewString = myString;` instead of `myNewString = duplicate(myString);` and the outcome is the same.  It would be nice to demonstrate the function with something where it's by reference and modifying a variable pointed at the original would mutate it,  followed by the same but with a `duplicate()` call to show that the outcome is different.

**Comment by shaedrich** [comment]
```
myString = 'Lorem ipsum';

myNewString = myString;
myOtherNewString = duplicate(myString);
    
myNewString = 'ahmet sun';
myOtherNewString = 'dolor sit';
    
writeDump(myString);
writeDump(myNewString);
writeDump(myOtherNewString);
```

shows that the string isn't changed in any of the cases. On the other hand, this works:
```
myStruct = {'foo': 'Lorem ipsum', 'bar': 'baz'};

myNewStruct = myStruct;
myOtherNewStruct = duplicate(myStruct);
    
myNewStruct.foo = 'ahmet sun';
myOtherNewStruct.foo = 'dolor sit';
    
writeDump(myStruct);
writeDump(myNewStruct);
writeDump(myOtherNewStruct);
```

**Comment by jinglesthula** [comment]
That second example looks like it would better demonstrate the `duplicate` functionality.

Just to check on my understanding - I think in some languages string literals are objects that can be modified.  I'm not sure if ColdFusion is one of those.  My impression is that in CF, a variable assigned to a string holds a reference to it, but if you ever change that variable, what you're doing is simply pointing it to something else rather than leaving it pointing to the same string which itself is modified.

```
test = "foo";
test2 = test;
test &= " bar";
writeoutput(test);
writeoutput(test2);
// foo barfoo
```

I think in the above example, the `&=` is the equivalent of `test = "foo" & " bar";` where it's just creating another unique string and pointing `test` to it.  Does that sound right?

I'm not 100% sure on the language's string implementation or behavior and whether it's value or reference based.  In any case I think your 2nd example would be a useful one to include in the docs.

**Comment by shaedrich** [comment]
Yes, it looks like this.
