### ISSUE TITLE
Examples area

### ISSUE THREAD

**Issue by KrunchMuffin** [foundeo/cfdocs#864]
I just wanted to voice my opinion about the examples area. 

Having all the syntax closed by default is inconvenient especially when all the headings are the same with no clue as to what it is going to uncover. 
Also only allowed to have one open at a time is even more so. Now you can't compare one over another over another.

![image](https://user-images.githubusercontent.com/1037197/41076347-2539f7d0-69df-11e8-8432-2f71787e9fd3.png)

**Comment by shaedrich** [comment]
Got point!

Every contributor is told to not use a heading like this. That didn't look good before either.

But it would be good to

1.  Open the first one by default
2. Don't close panel when another one is opened

**Comment by KrunchMuffin** [comment]
How about an open all button? Cffile is an extreme example, but that's a
lot of clicking.

**Comment by shaedrich** [comment]
Do you just want to expand/collapse all examples back and forth?

**Comment by KrunchMuffin** [comment]
That would probably be easiest.

**Comment by pfreitag** [comment]
Thanks for bringing this up @KrunchMuffin 

I agree - I think we should open all by default unless there are more than X examples. When there are more than X examples I still think it is useful to open them by default but then maybe just have a way to collapse expand all.

**Comment by KrunchMuffin** [comment]
Sounds good to me.

**Comment by shaedrich** [comment]
So what do we consider as X? 5? 10?

**Comment by KrunchMuffin** [comment]
25 😊

**Comment by shaedrich** [comment]
That's much. How big is your screen, dude? 😂

**Comment by KrunchMuffin** [comment]
32. I just want them all open. But with expand\collapse button it will be
ok.

**Comment by shaedrich** [comment]
I got it that you want them all open. Then 42 would have been pure invention as well^^

We already agree to make a expand/collapse button. But as @pfreitag pointed out it would be too much to initially open all if they exceed a specific amount.
