### ISSUE TITLE
Make menus scrollable

### ISSUE THREAD

**Issue by KamasamaK** [foundeo/cfdocs#882]
Some of the top-level menus, like "Other", are quite long and can get cut off.

**Comment by shaedrich** [comment]
I suggested to group the guides into sub menus

**Comment by shaedrich** [comment]
@KamasamaK I don't know, what @pfreitag and you think about that…

**Comment by pfreitag** [comment]
Sounds ok to me.

**Comment by shaedrich** [comment]
scrolling our sub menus?

**Comment by pfreitag** [comment]
sub menus would probably be better than scrolling I think.

**Comment by pfreitag** [comment]
did you already put in a PR to make scrollable? That can work - it's not a huge concern for me.

**Comment by pfreitag** [comment]
Whatever you think is fine with me, I'm ok with scrolling if it is done and looks good to you.

**Comment by shaedrich** [comment]
Hmmm… I could test how sub menus would look like when I'm at home this evening. I guess, it's best if I post two screenshots so we can decide which one actually looks better.

**Comment by KamasamaK** [comment]
Submenus sound fine too if you can find a good organization/grouping scheme.

**Comment by shaedrich** [comment]
Addressed in #587
