### ISSUE TITLE
getMetricData

### ISSUE THREAD

**Issue by gavyjatt** [foundeo/cfdocs#911]
No Longer works in Lucee

**Comment by shaedrich** [comment]
"According to TryCF, it's been deprecated since before the last Railo release"

**Comment by pfreitag** [comment]
Thanks for the heads up -- so we need to update the engine metatdata for this, anyone want to go through the lucee github to see when it was removed? was it ever part of lucee?

**Comment by shaedrich** [comment]
It seems to exist in the newest release: https://github.com/lucee/Lucee/blob/5.3.1.48/core/src/main/java/lucee/runtime/functions/system/GetMetricData.java

**Comment by gavyjatt** [comment]
that function is actually saying that "This is Depreciated"

**Comment by pfreitag** [comment]
Yup it just throws an exception that says it is deprecated ... it looks like it was never implemented, even in railo it just threw an exception: https://trycf.com/gist/d6a5a1eda9a97c4b95852a0c6fa6e3ed/railo

**Comment by gavyjatt** [comment]
so it cannot be added as an enhancement
