### ISSUE TITLE
Link to Adobe docs on Evaluate() is now 404

### ISSUE THREAD

**Issue by Muzical84** [foundeo/cfdocs#927]
https://cfdocs.org/evaluate links to https://help.adobe.com/en_US/ColdFusion/9.0/Developing/WSc3ff6d0ea77859461172e0811cbec09d55-7fdf.html which no longer exists.

**Comment by KamasamaK** [comment]
It looks to have been relocated to [here](https://helpx.adobe.com/coldfusion/developing-applications/the-cfml-programming-language/using-expressions-and-number-signs/dynamic-expressions-and-dynamic-variables.html#AvoidingtheEvaluatefunction). Although it's not identical, it's mostly the same as the one you can still find at [archive.org](https://web.archive.org/web/20160513160930/https://help.adobe.com/en_US/ColdFusion/9.0/Developing/WSc3ff6d0ea77859461172e0811cbec09d55-7fdf.html).
