### ISSUE TITLE
cfqueryparam SQL type mapping table

### ISSUE THREAD

**Issue by AntiTcb** [foundeo/cfdocs#985]
May not be possible given the JSON structure of all of the pages, but I believe it'd be incredibly helpful for the cfqueryparam page to include the SQL type chart found on https://helpx.adobe.com/coldfusion/cfml-reference/coldfusion-tags/tags-p-q/cfqueryparam.html.

**Comment by shaedrich** [comment]
Are you sure, there is the string 'chart'? I can find any occurrence by using Ctrl + F…

**Comment by AntiTcb** [comment]
The page doesn't actually use the word chart, apologies. If you Ctrl + F for "The following table," it's about half-way down the page.

**Comment by shaedrich** [comment]
And you're sure you mean 'chart' not 'char'? Still can't find it. Maybe you can post a screenshot. I must be blind^^

**Comment by AntiTcb** [comment]
![image](https://user-images.githubusercontent.com/4700391/47170246-8ff60e80-d2d3-11e8-98d9-b69df4852540.png)
Partial screenshot of it; it's actually taller than my monitor.

**Comment by shaedrich** [comment]
I'm sorry, but I still can't see it. Could you just post the line where the word appears?

**Comment by AntiTcb** [comment]
I think you're misunderstanding what I'm trying to convey. I'm suggesting that a chart similar to the screenshot I posted above should be added to https://cfdocs.org/cfqueryparam to show a helpful SQL data type mapping to the `cfsqltype` attribute.

**Comment by shaedrich** [comment]
Oh, I got it. Sorry for that misunderstanding!

You could add a guide for that. Now guides can be linked. But guides can't have tables now. We're discussing to change the markdown parsing engine to support tables.

**Comment by pfreitag** [comment]
Yes, we can make a `cfsqltype` guide for this...
